#!/usr/bin/env python3
"""Embed a binary file in C: bin2c.py <input> <output.c> <symbol>

Writes `const unsigned char <symbol>[]` (4-byte aligned) and `const unsigned int <symbol>_size`.
Used for the 3DS vertex shader binary (picasso output).
"""
import sys


def main():
    src, dst, symbol = sys.argv[1:4]
    data = open(src, "rb").read()
    lines = [f"/* Generated by bin2c.py from {src.replace(chr(92), '/').split('/')[-1]} */",
             f"const unsigned char {symbol}[] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"const unsigned int {symbol}_size = {len(data)};")
    text = "\n".join(lines) + "\n"
    try:
        if open(dst).read() == text:
            return
    except OSError:
        pass
    open(dst, "w", newline="\n").write(text)


if __name__ == "__main__":
    main()
