#!/usr/bin/env python3
"""Give every N64 overlay its own data / bss section so it can be reset on load.

On the N64 an overlay's .data is copied from the ROM and its .bss cleared every
time a scene loads it, and game code relies on that (statics holding object
pointers are simply expected to be NULL again). Natively all overlays are
linked in at once, so each overlay's variables are collected into their own
section range, which the runtime restores from a boot-time snapshot.

Overlays are the `ovl<N>` code segments of the decomp's splat yaml.

Outputs in <out_dir>:
  ovl_<n>.h            section header, force-included into the overlay's sources
  port_overlays.cmake  source file -> header assignments
  port_overlay_table.c range markers and the ROM start -> range table

On COFF the header's #pragma data_seg / bss_seg does the work (clang's own
`#pragma clang section` loses the section name there). On ELF the header only
marks the compile command; tools/cc_overlay.py renames the object's sections
afterwards and the linker provides the range symbols.

Usage: gen_overlays.py <decomp_dir> <out_dir> <cxx_wrapper_dir> <splat_yaml_name>
"""
import os
import re
import sys


def parse_segments(decomp, yaml_name):
    """[(name, rom_start, [source paths without extension])] for the overlay code segments."""
    segments, current = [], None
    with open(os.path.join(decomp, yaml_name)) as f:
        for line in f:
            m = re.match(r"  - name:\s*([\w.]+)", line)
            if m:
                current = {"name": m.group(1), "start": None, "files": []}
                segments.append(current)
                continue
            if re.match(r"  - ", line):
                current = None  # some other top-level entry
                continue
            if current is None:
                continue
            m = re.match(r"    start:\s*(0x[0-9A-Fa-f]+)", line)
            if m:
                current["start"] = int(m.group(1), 16)
                continue
            m = re.match(r"\s+- \[\s*0x[0-9A-Fa-f]+\s*,\s*(c|\.data|\.rodata|\.bss)\s*,\s*([\w/.]+)\s*\]", line)
            if not m:
                m = re.match(r"\s+- \{.*type:\s*(c|\.data|\.rodata|\.bss)\s*,\s*name:\s*([\w/.]+)\s*\}", line)
            if m and m.group(2) not in current["files"]:
                current["files"].append(m.group(2))
    return [(s["name"], s["start"], s["files"]) for s in segments
            if re.fullmatch(r"ovl\d+", s["name"]) and s["start"] is not None]


def write_if_changed(path, text):
    try:
        if open(path).read() == text:
            return
    except FileNotFoundError:
        pass
    with open(path, "w", newline="\n") as f:
        f.write(text)


def main():
    decomp, out = os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2])
    cxx_dir = os.path.abspath(sys.argv[3]).replace("\\", "/")
    os.makedirs(out, exist_ok=True)
    segments = parse_segments(decomp, sys.argv[4])

    cmake = ["# Generated by gen_overlays.py - do not edit."]
    table = ["/* Generated by gen_overlays.py - do not edit. */",
             "#include <port_host.h>", ""]
    rows = []
    for index, (name, start, files) in enumerate(segments):
        tag = "%03d" % index
        # COFF sections sort by the text after `$`:
        # <tag>a (start marker) < <tag>m (variables) < <tag>z (end marker).
        write_if_changed(os.path.join(out, f"ovl_{tag}.h"),
                         f"/* {name}: generated by gen_overlays.py */\n"
                         f"#ifdef _WIN32\n"
                         f"#pragma data_seg(\".od${tag}m\")\n#pragma bss_seg(\".ob${tag}m\")\n"
                         f"#endif\n")
        header = os.path.join(out, f"ovl_{tag}.h").replace("\\", "/")
        for rel in files:
            src = os.path.join(decomp, "src", rel + ".c").replace("\\", "/")
            if not os.path.exists(src):
                continue
            # the source itself, and its C++ data wrapper if it is built as one
            for path in (src, f"{cxx_dir}/{os.path.basename(rel)}.cpp"):
                # COMPILE_FLAGS is passed through verbatim (COMPILE_OPTIONS would split the pair)
                cmake.append(f"set_source_files_properties(\"{path}\" PROPERTIES COMPILE_FLAGS "
                             f"\"-include \\\"{header}\\\"\")")
        table.append("#ifdef _WIN32")
        for kind in ("d", "b"):
            for edge in ("a", "z"):
                table.append(f"__attribute__((section(\".o{kind}${tag}{edge}\"))) char gPortOvl_{kind}{tag}{edge} = 0;")
        # ELF: the linker brackets each section; an overlay without variables has no section at all.
        table.append("#else")
        for kind in ("d", "b"):
            table.append(f"extern char __start_ov{kind}_{tag}[] __attribute__((weak)), "
                         f"__stop_ov{kind}_{tag}[] __attribute__((weak));")
            table.append(f"#define gPortOvl_{kind}{tag}a (*__start_ov{kind}_{tag})")
            table.append(f"#define gPortOvl_{kind}{tag}z (*__stop_ov{kind}_{tag})")
        table.append("#endif")
        # A SYOverlay names its overlay by the address of the <name>_ROM_START linker symbol.
        table.append(f"extern char {name}_ROM_START;")
        rows.append(f"    {{ &{name}_ROM_START, \"{name}\", &gPortOvl_d{tag}a, &gPortOvl_d{tag}z, &gPortOvl_b{tag}a, &gPortOvl_b{tag}z }},")
    table += ["", "const PortOverlay gPortOverlays[] =", "{"] + rows + ["};",
              f"const unsigned int gPortOverlaysNum = {len(rows)};", ""]
    write_if_changed(os.path.join(out, "port_overlays.cmake"), "\n".join(cmake) + "\n")
    write_if_changed(os.path.join(out, "port_overlay_table.c"), "\n".join(table))
    print(f"{len(segments)} overlays, {sum(len(s[2]) for s in segments)} sources -> {out}")


if __name__ == "__main__":
    main()
