"""Cover the code a symbol dump still misses, using a decomp's splat symbol lists.

For every .text input section of the GNU ld map (RSP microcode objects excluded), runs of
non-zero words that no function covers are split at the addresses the splat symbol files
name ("name = 0xADDR;"), and added as functions (unnamed pieces: func_<vram>).

    python3 splat_fill_gaps.py in.toml baserom.z64 game.map out.toml symbols/a.txt [symbols/b.txt ...]
"""
import re
import sys
import tomllib

in_path, rom_path, map_path, out_path, *sym_files = sys.argv[1:]
rom = open(rom_path, "rb").read()
dump = tomllib.load(open(in_path, "rb"))
secs = {s["name"]: s for s in dump["section"]}

named = {}
for path in sym_files:
    for line in open(path, errors="replace"):
        m = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*0x([0-9A-Fa-f]+)\s*;", line)
        if m:
            named.setdefault(int(m.group(2), 16), m.group(1))

texts, cur = [], None
for line in open(map_path, errors="replace"):
    m = re.match(r"^(\.\S+)\s", line)
    if m:
        cur = m.group(1)
        continue
    m = re.match(r"\s+\.text\s+0x([0-9a-f]+)\s+0x([0-9a-f]+)\s+(\S+\.o)\s*$", line)
    if m and cur in secs and "/data/rsp/" not in m.group(3):
        texts.append((cur, int(m.group(1), 16) & 0xFFFFFFFF, int(m.group(2), 16), m.group(3)))

names = {f["name"] for s in dump["section"] for f in s.get("functions", [])}
added = []
for sec_name, start, size, obj in texts:
    s = secs[sec_name]
    funcs = s.setdefault("functions", [])
    covered = bytearray(size)
    for f in funcs:
        for i in range(max(f["vram"], start) - start, min(f["vram"] + f["size"], start + size) - start):
            covered[i] = 1
    ro = s["rom"] + (start - s["vram"])
    code = rom[ro:ro + size]
    i = 0
    while i < size:
        if covered[i] or not any(code[i:i + 4]):
            i += 4
            continue
        j = i
        while j < size and not covered[j]:
            j += 4
        # split [i, j) at named addresses, trim trailing zero words of each piece
        cuts = sorted({start + i} | {a for a in named if start + i < a < start + j})
        for k, a in enumerate(cuts):
            b = cuts[k + 1] if k + 1 < len(cuts) else start + j
            while b > a and not any(code[b - start - 4:b - start]):
                b -= 4
            if b <= a:
                continue
            name = named.get(a, f"func_{a:08X}")
            if name in names:
                name = f"{name}_{a:08X}"
            names.add(name)
            funcs.append({"name": name, "vram": a, "size": b - a})
            added.append((name, a, b - a, obj))
        i = j
    s["functions"] = sorted(funcs, key=lambda f: f["vram"])

with open(out_path, "w", newline="\n") as o:
    o.write("# Autogenerated from an ELF via N64Recomp, plus IDO static functions (.mdebug) and\n"
            "# splat-named functions for the remaining uncovered code\n")
    for sec in dump["section"]:
        o.write(f'[[section]]\nname = "{sec["name"]}"\nrom = 0x{sec["rom"]:08X}\nvram = 0x{sec["vram"]:08X}\n'
                f'size = 0x{sec["size"]:X}\n\nfunctions = [\n')
        for f in sec.get("functions", []):
            o.write(f'    {{ name = "{f["name"]}", vram = 0x{f["vram"]:08X}, size = 0x{f["size"]:X} }},\n')
        o.write("]\n\n")
print(f"functions added from splat names: {len(added)}")
for name, a, n, obj in added:
    print(f"  {a:#010x} +{n:#6x} {name:28s} {obj}")
